template_path: remote-templates/GuardDutyMember.yaml
stack_name: guardduty-member
dependencies:
  - essentials
parameters:
  MasterAccountId: !ssm /infra/SecuritycentralAwsAccountId
  InvitationId: 7ab3d070757a69a548196c2a55c89830
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/GuardDutyMember.yaml --create-dirs -o remote-templates/GuardDutyMember.yaml"
