template_path: remote-templates/GuardDutyMember.yaml
stack_name: guardduty-member
dependencies:
  - essentials
parameters:
  MasterAccountId: !ssm /infra/LogcentralAwsAccountId
  InvitationId: 94b20c8f05e8a59c30e21165bb6f301c
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/GuardDutyMember.yaml --create-dirs -o remote-templates/GuardDutyMember.yaml"
