template_path: remote-templates/peer-route-config.yaml
stack_name: peer-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-3f28d957
  VpcPrivateRouteTable: rtb-63ce7e1f
  VpcPublicRouteTable: rtb-97ce7eeb
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/peer-route-config.yaml --create-dirs -o remote-templates/peer-route-config.yaml"
