template_path: remote-templates/vpc.yaml
stack_name: sage-new-default-vpc
parameters:
  VpcSubnetPrefix: "10.30"
  VpcName: sage-new-default-vpc
  PrivateSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
  PublicSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/vpc.yaml --create-dirs -o remote-templates/vpc.yaml"
