template_path: remote/vpc.yaml
stack_name: synapse-ops-vpc-v2
parameters:
  VpcSubnetPrefix: "10.30"
  VpcName: synapse-ops-vpc-v2
  PrivateSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
  PublicSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/vpc.yaml --create-dirs -o templates/remote/vpc.yaml"
